### PR TITLE
Resolve swiftly when referenced in compile commands

### LINKED ISSUE #2128: LSP stops working in editors (VSCode, Sublime Text, Zed) with swiftly toolchains, logs say "No language service for ..."
### Swift version

main-snapshot-2025-04-12 (as reported by swiftly list)

### Platform

macOS 15

### Editor

Tried all of VSCode, Sublime Text, Zed

### Description

Have swiftly managed nightly "main" toolchain, checkout a simple CMake project, in my case it's the "pico-blink-sdk" subfolder from <https://github.com/apple/swift-embedded-examples/tree/main/pico-blink-sdk>. Build it in terminal. Then open the IDE. All LSP seems to not work. Internal logs show (these are from Zed):

```
// Send:
{"jsonrpc":"2.0","id":2,"method":"textDocument/documentHighlight","params":{"textDocument":{"uri":"file:///Users/kuba/Documents/swift-embedded-examples/pico-blink-sdk/Main.swift"},"position":{"line":20,"character":26}}}
// Receive:
{"jsonrpc":"2.0","id":2,"error":{"code":-32001,"message":"No language service for 'file:\/\/\/Users\/kuba\/Documents\/swift-embedded-examples\/pico-blink-sdk\/Main.swift' found"}}
// Send:
{"jsonrpc":"2.0","id":3,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///Users/kuba/Documents/swift-embedded-examples/pico-blink-sdk/Main.swift"},"range":{"start":{"line":20,"character":26},"end":{"line":20,"character":26}},"context":{"diagnostics":[],"only":["","quickfix","refactor","refactor.extract","source"]}}}
// Receive:
{"jsonrpc":"2.0","id":3,"error":{"code":-32001,"message":"No language service for 'file:\/\/\/Users\/kuba\/Documents\/swift-embedded-examples\/pico-blink-sdk\/Main.swift' found"}}
// Send:
{"jsonrpc":"2.0","id":4,"method":"textDocument/documentHighlight","params":{"textDocument":{"uri":"file:///Users/kuba/Documents/swift-embedded-examples/pico-blink-sdk/Main.swift"},"position":{"line":22,"character":6}}}
// Receive:
{"error":{"code":-32001,"message":"No language service for 'file:\/\/\/Users\/kuba\/Documents\/swift-embedded-examples\/pico-blink-sdk\/Main.swift' found"},"jsonrpc":"2.0","id":4}
// Send:
{"jsonrpc":"2.0","id":5,"method":"textDocument/documentHighlight","params":{"textDocument":{"uri":"file:///Users/kuba/Documents/swift-embedded-examples/pico-blink-sdk/Main.swift"},"position":{"line":22,"character":6}}}
// Receive:
{"id":5,"error":{"code":-32001,"message":"No language service for 'file:\/\/\/Users\/kuba\/Documents\/swift-embedded-examples\/pico-blink-sdk\/Main.swift' found"},"jsonrpc":"2.0"}
// Send:
{"jsonrpc":"2.0","id":6,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///Users/kuba/Documents/swift-embedded-examples/pico-blink-sdk/Main.swift"},"range":{"start":{"line":22,"character":6},"end":{"line":22,"character":6}},"context":{"diagnostics":[],"only":["","quickfix","refactor","refactor.extract","source"]}}}
// Receive:
{"jsonrpc":"2.0","id":6,"error":{"code":-32001,"message":"No language service for 'file:\/\/\/Users\/kuba\/Documents\/swift-embedded-examples\/pico-blink-sdk\/Main.swift' found"}}
```

### Steps to Reproduce

_No response_

### Logging

_No response_

### PR DESCRIPTION
**Pull request by ahoppen**
When the compiler in `compile_commands.json` references a `swift` executable that’s a symlink to `swiftly`, SourceKit-LSP got confused because the `swift` executable doesn’t reside in a real toolchain, causing us to not provide any semantic functionality.

When we discover that the `swift` executable reference in compile commands references a `swiftly` executable, use `swiftly use -p` to resolve the binary in the real toolchain and continue operating based on that.

Fixes #2128
rdar://150301344

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Review by hamishknight — APPROVED** [review]

File: Sources/BuildSystemIntegration/JSONCompilationDatabaseBuildSystem.swift [hunk 1]
```diff
@@ -131,10 +153,14 @@ package actor JSONCompilationDatabaseBuildSystem: BuiltInBuildSystem {
...
 
-  package func didChangeWatchedFiles(notification: OnWatchedFilesDidChangeNotification) {
+  package func didChangeWatchedFiles(notification: OnWatchedFilesDidChangeNotification) async {
     if notification.changes.contains(where: { $0.uri.fileURL?.lastPathComponent == Self.dbName }) {
       self.reloadCompilationDatabase()
     }
+    if notification.changes.contains(where: { $0.uri.fileURL?.lastPathComponent == ".swift-version" }) {
+      await swiftlyResolver.clearCache()
+      connectionToSourceKitLSP.send(OnBuildTargetDidChangeNotification(changes: nil))
+    }
```
Comment (bnbarham) [inline Sources/BuildSystemIntegration/JSONCompilationDatabaseBuildSystem.swift:163]: There would still be the case that the global version changes 🤔. Maybe that's fine though, ie. the answer there is to restart.

**Review by bnbarham — APPROVED** [review]
