### PR TITLE
Fix quadratic performance issue in `AsyncQueue<Serial>`

### LINKED ISSUE #1725: Quadratic performance issue in `AsyncQueue`
Adding an item to `AsyncQueue<Serial>` is linear in the number of pending queue items, thus adding n items to an `AsyncQueue` before any can execute is in O(n^2). This decision was made intentionally because the primary use case for `AsyncQueue` was to track pending LSP requests, of which we don’t expect to have too many pending requests at any given time.

But we should be able to resolve the quadratic issue of `AsyncQueue<Serial>` by making a new task only depend on the last item in the queue, which then transitively depends on all the previous items.

### PR DESCRIPTION
**Pull request by ahoppen**
Adding an item to `AsyncQueue` was linear in the number of pending queue items, thus adding n items to an `AsyncQueue` before any can execute is in O(n^2). This decision was made intentionally because the primary use case for `AsyncQueue` was to track pending LSP requests, of which we don’t expect to have too many pending requests at any given time.

While we can't fix the quadratic performance issue in general, we can resolve the quadratic issue of `AsyncQueue<Serial>` by making a new task only depend on the last item in the queue, which then transitively depends on all the previous items. `AsyncQueue<Serial>` are the queues that are most likely to contain many items.

Fixes #1725
rdar://137886469

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

File: Sources/SwiftExtensions/AsyncQueue.swift [hunk 1]
```diff
@@ -28,28 +28,31 @@ extension Task: AnyTask {
 
 /// A type that is able to track dependencies between tasks.
 package protocol DependencyTracker: Sendable {
-  /// Whether the task described by `self` needs to finish executing before
-  /// `other` can start executing.
-  func isDependency(of other: Self) -> Bool
```
Comment (hamishknight) [inline Sources/SwiftExtensions/AsyncQueue.swift:33]: Could keep both requirements and add a default implementation of `dependencies(in:)` that does the filtering. Don't really mind though

**Review by hamishknight — APPROVED** [review]

File: Sources/SwiftExtensions/AsyncQueue.swift (hunk 1 above)
Comment (ahoppen) [reply Sources/SwiftExtensions/AsyncQueue.swift:33]: I think it’s good to make adopters a little more aware of the potentially quadratic issue.
